=== gallowdd/Persephone/persephone-helper/build/resources/main/pantherBRACEProperties.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://pantherbrace.cs2550.pitt.edu/pantherBRACEProperties"
            xmlns="http://pantherbrace.cs2550.pitt.edu/pantherBRACEProperties"
            elementFormDefault="qualified">
    
    <xsd:element name="panther_brace_properties" type="pantherBracePropertiesType"/>
    
    <xsd:complexType name="pantherBracePropertiesType" mixed="true">
        <xsd:sequence>
            <xsd:element name="program_filenames" minOccurs="1" maxOccurs="1" type="programFilenameType"/>
            <xsd:element name="tables" minOccurs="1" maxOccurs="1" type="tableNameType"/>
            <xsd:element name="buffer_pages" minOccurs="1" maxOccurs="1" type="xsd:integer"/>
            <xsd:element name="random_number_seed" minOccurs="1" maxOccurs="1" type="xsd:integer"/>
            <xsd:element name="transaction_manager_type" minOccurs="1" maxOccurs="1" type="transactionManagerReadType"/>
        </xsd:sequence>
    </xsd:complexType>
  
    <xsd:complexType name="programFilenameType">   
        <xsd:sequence> 
            <xsd:element name="program_filename" minOccurs="1" maxOccurs="unbounded" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="tableNameType">   
        <xsd:sequence> 
            <xsd:element name="table" minOccurs="1" maxOccurs="unbounded" type="xsd:string"/>      
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="transactionManagerReadType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="WEIGHTED_ROUND_ROBIN"/>
            <xsd:enumeration value="RANDOM"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== gallowdd/Persephone/PersephoneHelper/src/main/resources/defaultProps.xml
<?xml version="1.0" encoding="UTF-8"?>
<panther_brace_properties xmlns="http://pantherbrace.cs2550.pitt.edu/pantherBRACEProperties"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://pantherbrace.cs2550.pitt.edu/pantherBRACEProperties pantherBRACEProperties.xsd">
    <program_filenames>
        <program_filename>/Users/ddg5/Desktop/Temp/LoadX.txt</program_filename>
        <program_filename>/Users/ddg5/Desktop/Temp/LoadY.txt</program_filename>
    </program_filenames>
    <tables>
        <table>X</table>
        <table>Y</table>
    </tables>
    <buffer_pages>2</buffer_pages>
    <random_number_seed>12345</random_number_seed>
    <transaction_manager_type>RANDOM</transaction_manager_type>
</panther_brace_properties>
