=== gallowdd/Persephone/persephone-lib/src/main/resources/schema/persephoneBaseParameters.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:common="http://persephone.gallowdd.pitt.edu/xml/common"
    targetNamespace="http://persephone.gallowdd.pitt.edu/xml/base"
    xmlns="http://persephone.gallowdd.pitt.edu/xml/base"
    elementFormDefault="qualified">
    
   <xsd:import namespace="http://persephone.gallowdd.pitt.edu/xml/common" schemaLocation="persephoneCommon.xsd"/>
  
  <xsd:element name="persephone_base_parameters">
    <xsd:complexType mixed="false">
      <xsd:sequence>
        <xsd:element name="agent" minOccurs="2" maxOccurs="2" type="agentXmlType" />
        <xsd:element name="location" minOccurs="1" maxOccurs="unbounded" type="locationXmlType" />
        <xsd:element name="network" minOccurs="0" maxOccurs="unbounded" type="networkXmlType" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:complexType name="agentXmlType">
    <xsd:sequence>
      <xsd:element name="data_type" minOccurs="1" maxOccurs="1" type="common:agentDatatypeXmlEnum" />
      <xsd:element name="filename" minOccurs="1" maxOccurs="1" type="common:agentFilenameXmlEnum" />
      <xsd:element name="agent_attribute" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="data_type" minOccurs="1" maxOccurs="1" type="common:datatypeXmlEnum" />
            <xsd:element name="source" minOccurs="0" maxOccurs="1">
              <!-- The way to assign attributes to agents that are in the initial population files -->
              <xsd:complexType>
                <xsd:choice>
                  <!-- The initialization file for agents has a field with this information -->
                  <xsd:element name="initial_file" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                      <xsd:sequence>
                        <xsd:element name="csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="convert_to_enum_function" minOccurs="0" maxOccurs="1" type="xsd:string" />
                      </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
                  <!-- The initialization file for agents does NOT have a field with this information, 
                       so there will be a separate file with agent ID and this field -->
                  <xsd:element name="link_file" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                      <xsd:sequence>
                        <xsd:element name="filename" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="convert_to_enum_function" minOccurs="0" maxOccurs="1" type="xsd:string" />
                      </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
                </xsd:choice>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="attr_name" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>
<!--       <xsd:element name="agent_assignment" minOccurs="0" maxOccurs="unbounded" type="agentAssignmentType" /> -->
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:ID" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="locationXmlType">
    <xsd:sequence>
      <xsd:element name="data_type" minOccurs="1" maxOccurs="1" type="common:locationDatatypeXmlEnum" />
      <xsd:element name="filename" minOccurs="1" maxOccurs="1" type="common:locationFilenameXmlEnum" />
      <xsd:element name="latitude" minOccurs="1" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="longitude" minOccurs="1" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="elevation" minOccurs="0" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="location_attribute" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="data_type" minOccurs="1" maxOccurs="1" type="common:datatypeXmlEnum" />
            <xsd:element name="source" minOccurs="0" maxOccurs="1">
              <xsd:complexType>
                <xsd:choice>
                  <!-- The initialization file for locations has a field with this information -->
                  <xsd:element name="initial_file" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                      <xsd:sequence>
                        <xsd:element name="csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="convert_to_enum_function" minOccurs="0" maxOccurs="1" type="xsd:string" />
                      </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
                  <!-- The initialization file for location does NOT have a field with this information, 
                       so there will be a separate file with location ID and this field -->
                  <xsd:element name="link_file" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                      <xsd:sequence>
                        <xsd:element name="filename" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="convert_to_enum_function" minOccurs="0" maxOccurs="1" type="xsd:string" />
                      </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
                </xsd:choice>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="attr_name" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>
<!--       <xsd:element name="agent_assignment" minOccurs="0" maxOccurs="unbounded" type="agentAssignmentType" /> -->
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:ID" use="required"/>
  </xsd:complexType>
  
    <xsd:complexType name="networkXmlType">
    <xsd:sequence>
      <xsd:element name="data_type" minOccurs="1" maxOccurs="1" type="common:networkDatatypeXmlEnum" />
      <xsd:element name="filename" minOccurs="1" maxOccurs="1" type="xsd:string" />
      <xsd:element name="network_attribute" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="data_type" minOccurs="1" maxOccurs="1" type="common:datatypeXmlEnum" />
            <xsd:element name="source" minOccurs="0" maxOccurs="1">
              <xsd:complexType>
                <xsd:choice>
                  <!-- The initialization file for locations has a field with this information -->
                  <xsd:element name="initial_file_link" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                      <xsd:sequence>
                        <xsd:element name="init_file_csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="convert_to_enum_function" minOccurs="0" maxOccurs="1" type="xsd:string" />
                      </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
                  <!-- The initialization file for location does NOT have a field with this information, 
                       so there will be a separate file with location ID and this field -->
                  <xsd:element name="link" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                      <xsd:sequence>
                        <xsd:element name="link_file_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="link_file_csv_field_name" minOccurs="1" maxOccurs="1" type="xsd:string" />
                        <xsd:element name="convert_to_enum_function" minOccurs="0" maxOccurs="1" type="xsd:string" />
                      </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
                </xsd:choice>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="attr_name" type="common:networkDatatypeXmlEnum" use="required"/>
        </xsd:complexType>
      </xsd:element>
<!--       <xsd:element name="agent_assignment" minOccurs="0" maxOccurs="unbounded" type="agentAssignmentType" /> -->
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:ID" use="required"/>
  </xsd:complexType>
</xsd:schema>

=== gallowdd/Persephone/persephone-lib/bin/main/persephoneBaseParams.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  File: persephoneBaseParameters.xml
  Description: Parameters that will only be modified by developers
-->
<b:persephone_base_parameters
    xmlns:b="http://persephone.gallowdd.pitt.edu/xml/base"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://persephone.gallowdd.pitt.edu/xml/base schema/persephoneBaseParameters.xsd">
  <b:agent name="Person">
    <b:data_type>Person</b:data_type>
    <b:filename>people.csv</b:filename>
    <b:agent_attribute attr_name="initAge">
      <b:data_type>int</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>age</b:csv_field_name>
        </b:initial_file>
      </b:source>
    </b:agent_attribute>
    <b:agent_attribute attr_name="sex">
      <b:data_type>String</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>sex</b:csv_field_name>
          <b:convert_to_enum_function>stringToSexEnum</b:convert_to_enum_function>
        </b:initial_file>
      </b:source>
    </b:agent_attribute>
    <b:agent_attribute attr_name="race">
      <b:data_type>int</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>race_code</b:csv_field_name>
          <b:convert_to_enum_function>intToRaceEnum</b:convert_to_enum_function>
        </b:initial_file>
      </b:source>
    </b:agent_attribute>
    <b:agent_attribute attr_name="relationship">
      <b:data_type>int</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>relationship_code</b:csv_field_name>
          <b:convert_to_enum_function>intToRelationshipEnum</b:convert_to_enum_function>
        </b:initial_file>
      </b:source>
    </b:agent_attribute>
  </b:agent>
  <b:agent name="GroupQuartersPerson">
    <b:data_type>Person</b:data_type>
    <b:filename>gq_people.csv</b:filename>
    <b:agent_attribute attr_name="initAge">
      <b:data_type>int</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>age</b:csv_field_name>
        </b:initial_file>
      </b:source>
    </b:agent_attribute>
    <b:agent_attribute attr_name="sex">
      <b:data_type>String</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>sex</b:csv_field_name>
          <b:convert_to_enum_function>stringToSexEnum</b:convert_to_enum_function>
        </b:initial_file>
      </b:source>
    </b:agent_attribute>
    <b:agent_attribute attr_name="race">
      <b:data_type>int</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>race_code</b:csv_field_name>
          <b:convert_to_enum_function>intToRaceEnum</b:convert_to_enum_function>
        </b:initial_file>
      </b:source>
    </b:agent_attribute>
    <b:agent_attribute attr_name="relationship">
      <b:data_type>int</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>relationship_code</b:csv_field_name>
          <b:convert_to_enum_function>intToRelationshipEnum</b:convert_to_enum_function>
        </b:initial_file>
      </b:source>
    </b:agent_attribute>
  </b:agent>
  
  <b:location name="Household">
    <b:data_type>Household</b:data_type>
    <b:filename>households.csv</b:filename>
    <b:latitude>
      <b:csv_field_name>latitude</b:csv_field_name>
    </b:latitude>
    <b:longitude>
      <b:csv_field_name>longitude</b:csv_field_name>
    </b:longitude>
    <b:elevation>
      <b:csv_field_name>elevation</b:csv_field_name>
    </b:elevation>
    <b:location_attribute attr_name="stateFipsCode">
      <b:data_type>String</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>state_fips_cd</b:csv_field_name>
        </b:initial_file>
      </b:source>
    </b:location_attribute>
    <b:location_attribute attr_name="countyFipsCode">
      <b:data_type>String</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>county_fips_cd</b:csv_field_name>
        </b:initial_file>
      </b:source>
    </b:location_attribute>
    <b:location_attribute attr_name="tractFipsCode">
      <b:data_type>String</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>tract_fips_cd</b:csv_field_name>
        </b:initial_file>
      </b:source>
    </b:location_attribute>
    <b:location_attribute attr_name="householdIncome">
      <b:data_type>double</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>hh_income</b:csv_field_name>
        </b:initial_file>
      </b:source>
    </b:location_attribute>
  </b:location>
  <b:location name="Workplace">
    <b:data_type>Workplace</b:data_type>
    <b:filename>workplaces.csv</b:filename>
    <b:latitude>
      <b:csv_field_name>latitude</b:csv_field_name>
    </b:latitude>
    <b:longitude>
      <b:csv_field_name>longitude</b:csv_field_name>
    </b:longitude>
    <b:elevation>
      <b:csv_field_name>elevation</b:csv_field_name>
    </b:elevation>
  </b:location>
  <b:location name="School">
    <b:data_type>School</b:data_type>
    <b:filename>schools.csv</b:filename>
    <b:latitude>
      <b:csv_field_name>latitude</b:csv_field_name>
    </b:latitude>
    <b:longitude>
      <b:csv_field_name>longitude</b:csv_field_name>
    </b:longitude>
    <b:elevation>
      <b:csv_field_name>elevation</b:csv_field_name>
    </b:elevation>
    <b:location_attribute attr_name="stateFipsCode">
      <b:data_type>String</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>state_fips_cd</b:csv_field_name>
        </b:initial_file>
      </b:source>
    </b:location_attribute>
    <b:location_attribute attr_name="countyFipsCode">
      <b:data_type>String</b:data_type>
      <b:source>
        <b:initial_file>
          <b:csv_field_name>county_fips_cd</b:csv_field_name>
        </b:initial_file>
      </b:source>
    </b:location_attribute>
  </b:location>
</b:persephone_base_parameters>
