=== gallowdd/Persephone/PersephoneLib/src/main/resources/schema/persephoneSyntheticEnvironment.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:common="http://persephone.gallowdd.pitt.edu/xml/common"
    targetNamespace="http://persephone.gallowdd.pitt.edu/xml/synthenv"
    xmlns="http://persephone.gallowdd.pitt.edu/xml/synthenv" 
    elementFormDefault="qualified">
    
  <xsd:import namespace="http://persephone.gallowdd.pitt.edu/xml/common" schemaLocation="persephoneCommon.xsd"/>
  
  <xsd:element name="synthetic_environment">
    <xsd:complexType mixed="false">
      <xsd:sequence>
        <xsd:element name="identifier" minOccurs="1" maxOccurs="1" type="xsd:string" />
        <xsd:element name="country" minOccurs="1" maxOccurs="1" type="common:countryCodeXmlEnum" />
        <xsd:element name="version" minOccurs="1" maxOccurs="1" type="common:popVersionXmlEnum" />
        <xsd:element name="agent" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="agent_type" minOccurs="1" maxOccurs="1" type="common:agentDatatypeXmlEnum" />
              <xsd:element name="filename" minOccurs="1" maxOccurs="1" type="common:agentFilenameXmlEnum" />
              <xsd:element name="entry_count" minOccurs="1" maxOccurs="1" type="xsd:integer" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="location" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="location_type" minOccurs="1" maxOccurs="1" type="common:locationDatatypeXmlEnum" />
              <xsd:element name="filename" minOccurs="1" maxOccurs="1" type="common:locationFilenameXmlEnum" />
              <xsd:element name="entry_count" minOccurs="1" maxOccurs="1" type="xsd:integer" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
</xsd:schema>

=== gallowdd/Persephone/PersephoneLib/src/main/resources/syntheticEnvironmentInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<env:synthetic_environment 
    xmlns:c="http://persephone.gallowdd.pitt.edu/xml/common" 
    xmlns:env="http://persephone.gallowdd.pitt.edu/xml/synthenv" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://persephone.gallowdd.pitt.edu/xml/synthenv schema/persephoneSyntheticEnvironment.xsd">
    <env:identifier>01003</env:identifier>
    <env:country>USA</env:country>
    <env:version>Persephone.v1.0</env:version>
    <env:agent>
        <env:agent_type>Person</env:agent_type>
        <env:filename>people.csv</env:filename>
        <env:entry_count>9227</env:entry_count>
    </env:agent>
    <env:agent>
        <env:agent_type>Person</env:agent_type>
        <env:filename>gq_people.csv</env:filename>
        <env:entry_count>1642</env:entry_count>
    </env:agent>
    <env:location>
        <env:location_type>Household</env:location_type>
        <env:filename>households.csv</env:filename>
        <env:entry_count>3745</env:entry_count>
    </env:location>
    <env:location>
        <env:location_type>School</env:location_type>
        <env:filename>schools.csv</env:filename>
        <env:entry_count>9</env:entry_count>
    </env:location>
    <env:location>
        <env:location_type>Workplace</env:location_type>
        <env:filename>workplaces.csv</env:filename>
        <env:entry_count>1356</env:entry_count>
    </env:location>
    <env:location>
        <env:location_type>CollegeDorm</env:location_type>
        <env:filename>college_dorms.csv</env:filename>
        <env:entry_count>0</env:entry_count>
    </env:location>
    <env:location>
        <env:location_type>NursingFacility</env:location_type>
        <env:filename>nursing_facilities.csv</env:filename>
        <env:entry_count>1</env:entry_count>
    </env:location>
    <env:location>
        <env:location_type>Prison</env:location_type>
        <env:filename>prisons.csv</env:filename>
        <env:entry_count>3</env:entry_count>
    </env:location>
    <env:location>
        <env:location_type>MilitaryBarracks</env:location_type>
        <env:filename>military_barracks.csv</env:filename>
        <env:entry_count>0</env:entry_count>
    </env:location>
</env:synthetic_environment>
